#!/bin/bash

IMAGE_SOURCE_DIR="source_images"
IMAGE_DEST_DIR="customized_images"

RASPBIAN_DIR_DATE="2020-02-14"
RASPBIAN_IMAGE_DATE="2020-02-13"

RASPBIAN_IMAGE="${RASPBIAN_IMAGE_DATE}-raspbian-buster-lite.zip"
RASPBIAN_SHA256="${RASPBIAN_IMAGE_DATE}-raspbian-buster-lite.zip.sha256"
RASPBIAN_BASE_URL="https://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-${RASPBIAN_DIR_DATE}"

(cd $IMAGE_SOURCE_DIR && curl -O ${RASPBIAN_BASE_URL}/${RASPBIAN_IMAGE})
(cd $IMAGE_SOURCE_DIR && curl -O ${RASPBIAN_BASE_URL}/${RASPBIAN_SHA256})

SHA_FILE="${IMAGE_SOURCE_DIR}/${RASPBIAN_SHA256}"
IMAGE_FILE="${IMAGE_SOURCE_DIR}/${RASPBIAN_IMAGE}"

cat $SHA_FILE

CHECKSUM=$(awk '{ print $1 }' ${SHA_FILE}) && \
    echo "$CHECKSUM ${IMAGE_FILE}" > checksum.txt && \
    cat checksum.txt && \
    sha256sum -c checksum.txt

unzip ${IMAGE_FILE} -d ${IMAGE_SOURCE_DIR}

rm -f ${IMAGE_FILE} ${SHA_FILE}
