#!/bin/bash

# Variables
CLIENT_NAME="testing"
WG_CONFIG_DIR="wg_configs"
SERVER_PUBLIC_KEY="815JJkrmg9DcD7biV0s+iQTFeCjvG8I84kwttKteM2s="
SERVER_ENDPOINT="129.116.71.233:51820"
CLIENT_PRIVATE_KEY=""
CLIENT_PUBLIC_KEY=""

# Create WireGuard configuration directory if it doesn't exist
mkdir -p ${WG_CONFIG_DIR}

# Generate client private and public keys
CLIENT_PRIVATE_KEY=$(wg genkey)
CLIENT_PUBLIC_KEY=$(echo ${CLIENT_PRIVATE_KEY} | wg pubkey)

# Function to generate a WireGuard configuration
generate_wg_config() {
    local private_key=$1
    local public_key=$2
    local address=$3

    cat <<EOL > ${WG_CONFIG_DIR}/${CLIENT_NAME}.conf
[Interface]
PrivateKey = ${private_key}
Address = ${address}/24
DNS = 10.0.0.1

[Peer]
PublicKey = ${SERVER_PUBLIC_KEY}
Endpoint = ${SERVER_ENDPOINT}
AllowedIPs = 10.0.0.0/16
PersistentKeepalive = 25
EOL
}

# Generate the configuration
generate_wg_config ${CLIENT_PRIVATE_KEY} ${CLIENT_PUBLIC_KEY} "10.0.0.2"

echo "Generated WireGuard configuration for ${CLIENT_NAME} in ${WG_CONFIG_DIR}/${CLIENT_NAME}.conf"

# Output the client public key
echo "Client Public Key: ${CLIENT_PUBLIC_KEY}"
