#!/bin/bash

# Since we have autologin, this will set an autologout 
# This gives you 10 minutes to access the system after reboot
# This will help with lost password, although it does give
# others an easy way to access the system by simply restarting it
# This is system-wide for all regular user accounts
# You can disable by typing "unset TMOUT"
sudo echo "TMOUT=600" > /etc/profile.d/autologout.sh
sudo echo "export TMOUT" >> /etc/profile.d/autologout.sh
sudo chmod +x /etc/profile.d/autologout.sh






