wg_ip: 10.123.0.2
source_dir: source_images
dest_dir: customized_images
image_file: raspios_lite_armhf-2024-03-15-lite.img
server_ip: 129.116.71.233
server_public_key: xxxx
autologin: 0
disable_wifi: 0
disable_bluetooth: 0
disable_triggerhappy: 0
aptcache: 
