#!/bin/bash

# Create and activate the virtual environment
python3 -m venv /home/biosense/biosense_venv
source /home/biosense/biosense_venv/bin/activate

# Upgrade pip to the latest version
pip install --upgrade pip

# For birdnetlib
pip install "numpy<2"

# Install wheel files
# for wheel_file in /home/biosense/python/*.whl; do
#     pip install "$wheel_file" && rm -f "$wheel_file"
# done

# Install additional dependencies from requirements.txt if it exists
if [ -f /home/biosense/python/requirements.txt ]; then
    pip install -r /home/biosense/python/requirements.txt
fi

echo "Setup complete."
