#!/bin/bash
#
# This is an sdm plugin for: sdm-biosense-init-image
#
# The plugin is called three times: for Phase 0, Phase 1, and post-install.
#

function loadparams() {
    source $SDMPT/etc/sdm/sdm-readparams
}

# $1 is the phase: "0", "1", or "post-install"
# $2 is the argument list: arg1=val1|arg2=val2|arg3=val3| ...
#
# Main code for the Plugin
#
phase=$1
pfx="$(basename $0)" #For messages
args="$2"
loadparams
vldargs="" # |list|of|valid|args|or|nullstring|
rqdargs="" # |list|of|required|args|or|nullstring|
assetdir="$SDMPT/etc/sdm/assets/$pfx"

# Set the WireGuard interface name
WG_INTERFACE="biosense"

# Helper function to copy file trees
copy_and_set_ownership() {
    local src_dir=$1
    local dest_dir=$2
    local owner=$3
    local group=$4

    if [ -d "$src_dir" ]; then
        find "$src_dir" | while read -r src_item; do
            # Get the relative path of the item from the source directory
            rel_path="${src_item#$src_dir}"
            dest_item="$dest_dir$rel_path"

            # Check if the item exists in the destination
            if [ ! -e "$dest_item" ]; then
                if [ -d "$src_item" ]; then
                    # Create the directory in the destination
                    mkdir -p "$dest_item"
                    chown "$owner:$group" "$dest_item"
                elif [ -f "$src_item" ]; then
                    # Copy the file to the destination
                    cp "$src_item" "$dest_item"
                    chown "$owner:$group" "$dest_item"
                fi
            fi
        done
    else
        logtoboth "No files found in $src_dir"
    fi
}

if [ "$phase" == "0" ]; then
    #
    # In Phase 0 all references to directories in the image must be preceded by $SDMPT
    #
    logtoboth "* Plugin $pfx: Start Phase 0"
    plugin_getargs $pfx "$args" "$vldargs" "$rqdargs" || exit
    #
    # Print the keys found (example usage). plugin_getargs returns the list of found keys in $foundkeys
    #
    plugin_printkeys
    mkdir -p $assetdir

    # Biosense is not defined and 1000 *should* be the first user
    copy_and_set_ownership /home/agent/hostdir/files/home/biosense $SDMPT/home/biosense 1000 1000

    # Copy etc files
    copy_and_set_ownership /home/agent/hostdir/files/etc $SDMPT/etc root root

    # Copy usr/local files
    copy_and_set_ownership /home/agent/hostdir/files/usr/local $SDMPT/usr/local root root

    # Copy var files
    copy_and_set_ownership /home/agent/hostdir/files/var/log $SDMPT/var/log 1000 1000

    logtoboth "Copied files to image"

    logtoboth "* Plugin $pfx: Complete Phase 0"

elif [ "$phase" == "1" ]; then
    #
    # Phase 1 (in nspawn)
    #
    logtoboth "* Plugin $pfx: Start Phase 1"
    plugin_getargs $pfx "$args" "$vldargs" "$rqdargs"
    #logfreespace "at start of Plugin $pfx Phase 1"

    raspi-config nonint do_change_locale C.UTF-8 &&
        logtoboth "Set locale to C.UTF-8"

    raspi-config nonint do_configure_keyboard 'Generic 104-key PC' &&
        logtoboth "Set keymap to Generic 104-key PC"

    # Create a virtual environment and install packages from requirements.txt
    sudo -u biosense /home/biosense/python/setup-python

    logtoboth "Created virtual environment and installed packages for biosense user from requirements.txt"

    logtoboth "* Plugin $pfx: Complete Phase 1"

elif [ "$phase" == "post-install" ]; then
    #
    # Plugin Post-install edits
    #
    logtoboth "* Plugin $pfx: Start Phase post-install"
    plugin_getargs $pfx "$args" "$vldargs" "$rqdargs"
    #logfreespace "at start of Plugin $pfx Phase post-install"

    logtoboth "* Plugin $pfx: Complete Phase post-install"
fi

echo "done."
exit 0
