#!/bin/bash

IMAGE_SOURCE_DIR="source_images"
IMAGE_DEST_DIR="customized_images"
OVERWRITE=0
DEBUG=0

# Function to display usage information
usage() {
    echo "Usage: $0 [--source-dir <dir>] [--dest-dir <dir>] [--image-file <file>] [--overwrite] [--debug]"
    echo "  --source-dir <dir>  : Specify the directory for the source images (default: source_images)."
    echo "  --dest-dir <dir>    : Specify the directory for the customized images (default: customized_images)."
    echo "  --image-file <file> : Path to the source image file. Can be a full path or just the filename."
    echo "  --overwrite         : Overwrite the customized image file if it exists."
    echo "  --debug             : Run sdm without --batch option."
    exit 1
}

# Parse command line arguments
while [[ "$#" -gt 0 ]]; do
    case $1 in
    --source-dir)
        IMAGE_SOURCE_DIR=$2
        shift
        ;;
    --dest-dir)
        IMAGE_DEST_DIR=$2
        shift
        ;;
    --image-file)
        IMAGE_FILE=$(basename "$2")
        shift
        ;;
    --overwrite)
        OVERWRITE=1
        ;;
    --debug)
        DEBUG=1
        ;;
    *)
        echo "Invalid option: $1" 1>&2
        usage
        ;;
    esac
    shift
done

if [[ -z "${IMAGE_FILE}" ]]; then
    IMAGE_FILE=$(ls -t ${IMAGE_SOURCE_DIR}/*.img 2>/dev/null | head -n 1)
    if [[ -z "$IMAGE_FILE" ]]; then
        echo "No image files found in the source directory."
        exit 1
    fi
    IMAGE_FILE=$(basename "$IMAGE_FILE")
fi

CUSTOMIZED_IMAGE_FILE="${IMAGE_DEST_DIR}/${IMAGE_FILE}"

if [[ -f "${CUSTOMIZED_IMAGE_FILE}" ]]; then
    if [[ ${OVERWRITE} -eq 1 ]]; then
        echo "Overwriting existing file: ${CUSTOMIZED_IMAGE_FILE}"
        cp -a -f "${IMAGE_SOURCE_DIR}/${IMAGE_FILE}" "${CUSTOMIZED_IMAGE_FILE}"
    else
        echo "Customized image file already exists and overwrite option not set. Exiting."
        exit 1
    fi
else
    cp -a -f "${IMAGE_SOURCE_DIR}/${IMAGE_FILE}" "${CUSTOMIZED_IMAGE_FILE}"
fi

DOCKER_IMAGE_NAME="biosense-sdm"
docker build -t "${DOCKER_IMAGE_NAME}" .

SDM_COMMAND="sudo sdm --customize --extend --xmb 4096"
if [[ ${DEBUG} -eq 0 ]]; then
    SDM_COMMAND="${SDM_COMMAND} --batch"
fi

# Add the necessary plugins to the sdm command
SDM_COMMAND="${SDM_COMMAND} \
    --chroot \
    --plugin @/home/agent/hostdir/sdm-plugin-commands \
    --plugin /home/agent/hostdir/init-biosense-image-plugin \
    /home/agent/hostdir/${CUSTOMIZED_IMAGE_FILE}"

docker run --privileged -it --rm -v "$(pwd)":/home/agent/hostdir -v /dev:/dev "${DOCKER_IMAGE_NAME}" /bin/bash -c "${SDM_COMMAND}"

exit 0
